server:
  port: 8080
eureka:
  instance:
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://peer2:8084/eureka/
  server:
    enable-self-preservation: false